apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app_name: myapp
    namespace: ns-dev
  name: myapp-dp
  namespace: ns-dev
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
     metadata:
       annotations:
         app_name: myapp
         namespace: ns-dev
       namespace: ns-dev
       labels:
         app: myapp
     spec:
        containers:
          - name: myapp
            image: farhinacr1.azurecr.io/farhinacr1:latest
            resources:
              limits:
                memory: "128Mi"
                cpu: "500m"
            ports:
              - containerPort: 8080
                protocol: 'TCP'

---

apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  namespace: ns-dev
spec:
  type: ClusterIP
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080





