apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-dp
  namespace: ns-dev
spec:
  selector:
    matchLabels:
      app: myapp-dp
  template:
    metadata:
      labels:
        app: myapp-dp
    spec:
      containers:
      - name: myapp-dp
        image: farhinacr1.azureacr.io/
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
spec:
  type: LoadBalancer
  selector:
    app: myapp-dp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080






